print("Hello World!")
print(10*10)


print("        ★           ")
print("        /\          ")
print("       / *\         ")
print("      / 0  \        ")
print("     /  * 0 \       ")
print("    / 0  0   \      ")
print("   /__________\     ")
print("       |▲ ▲|        ")
print("      _|___|_       ")
print("     |       |      ")
print("     |       |      ")
print("     |_______|      ")
